#ifndef HOOK_FILEAPI_H
#define HOOK_FILEAPI_H
#include <windows.h>
#include <stdint.h>
typedef HANDLE (WINAPI *CreateFileW_t)(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
typedef HANDLE (WINAPI *CreateFileA_t)(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
typedef BOOL   (WINAPI *ReadFile_t)(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef DWORD  (WINAPI *GetFileSize_t)(HANDLE, LPDWORD);
typedef BOOL   (WINAPI *GetFileSizeEx_t)(HANDLE, PLARGE_INTEGER);
typedef DWORD  (WINAPI *GetFileAttributesA_t)(LPCSTR);
typedef DWORD  (WINAPI *GetFileAttributesW_t)(LPCWSTR);
HANDLE WINAPI Hook_CreateFileW(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
HANDLE WINAPI Hook_CreateFileA(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
BOOL   WINAPI Hook_ReadFile(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
DWORD  WINAPI Hook_GetFileSize(HANDLE, LPDWORD);
BOOL   WINAPI Hook_GetFileSizeEx(HANDLE, PLARGE_INTEGER);
DWORD  WINAPI Hook_GetFileAttributesA(LPCSTR);
DWORD  WINAPI Hook_GetFileAttributesW(LPCWSTR);
int32_t HookFile_Install(void);
#endif
